### ISSUE TITLE
Add a method to clear a store

### ISSUE THREAD

**Issue by vid** [Microsoft/NoSQLProvider#69]
There is currently a clearAllData method to clear all data, but there is no way to clear a particular data store without enumerating the existing data.

**Comment by deregtd** [comment]
@vid : There's a clearAllDAta method on the root provider, but that just loops through the stores and calls clearAllData on each of them:

https://github.com/Microsoft/NoSQLProvider/blob/a645dc722b70b93a5f57443c4f864427869bea5f/src/NoSqlProvider.ts#L85

**Comment by vid** [comment]
Thanks. I guess I was confused by the way it's used in a ReactXP example. 
Unrelatedly, you might want to check your use of the word "spurns" in the README, since your implementation is more a matter of appropriateness than contempt.
